export const site = {
  name: "Coen Claassen",
  title: "Coen Claassen | Product work and curiosity notes",
  description: "Physical and digital product work, Curiosity notes from conversations, and a little more about Coen Claassen.",
  url: "https://coenclaassen.com",
  locale: "en",
  ogImage: "/og/ogCoen.png",
  ogImageAlt: "Coen Claassen",
  ogImageWidth: 1200,
  ogImageHeight: 630,
  email: "coenclaassen@gmail.com",
  emailHref: "mailto:coenclaassen@gmail.com",
  contactCardEmail: "coenclaassen@gmail.com",
  phone: "+31639310529",
  whatsappHref: "https://wa.me/31639310529",
  linkedinHref: "https://www.linkedin.com/in/coenclaassen/",
  offTrailRunHref: "https://www.offtrailrun.com",
  knowsAbout: [
    "product development",
    "product engineering",
    "product leadership",
    "curiosity conversations",
    "running adventures",
    "orienteering",
  ],
} as const;
